### ISSUE TITLE
你好，科研新手，想知道哪里可以看到AAAI的审稿意见？另外，您这篇文章的审稿意见可以挂上来吗？

### ISSUE THREAD

**Issue by Ming-Qin-tech** [BIT-DA/EADA#1]

**Comment by BinhuiXie** [comment]
MetaReview:

The paper proposed a relative novel idea in active learning and domain adaptation through using the energy model. Specifically, in domain adaptation, they aim to align the energy of the source and target. In active learning, they select the samples with the largest margin approach in highest and second energy.  Extensive empirical results demonstrate the effectiveness of the proposed approach. The paper is well organized, clearly written and easy to follow. Reviewers agree that the proposed method addresses an important problem and is novel. The rebuttal addresses their remaining concerns. I therefore recommend acceptance for this paper.
