### ISSUE TITLE
RAND Active Function is Incomplete 

### ISSUE THREAD

**Issue by aminullah6264** [BIT-DA/EADA#2]
The RAND_active function does not return anything, how to complete this function to select Random active queries? 

https://github.com/BIT-DA/EADA/blob/ee4a5868d3dd4bd5488019a11150127e30a1047d/core/active/active.py#L7

**Comment by Zephyr-S** [comment]
Seems all the trainer is using 'EADA' instead of 'RAND' in config files. Maybe we don't have to consider the random situation at all I suppose.

**Comment by BinhuiXie** [comment]
Hi@Aminullah6264 

Thanks for your attention! We have fixed it (https://github.com/BIT-DA/EADA/commit/209af1791dd0e09e84d8e49c5d28a16345dfe3fe), please check.

**Comment by BinhuiXie** [comment]
I believe the issue at hand has been resolved, so I am closing this issue. If you have further questions, please feel free to ask.
